[workspace]
resolver = "2"
members = [
    "crates/qomicex-connector",
    "crates/qomicex-connector-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
tokio = { version = "1", features = ["net", "io-util", "time", "sync", "macros", "rt", "rt-multi-thread", "signal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
log = "0.4"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
rand = { version = "0.8", features = ["std_rng"] }
uuid = { version = "1", features = ["v4"] }
cidr = { version = "0.3.1", features = ["serde"] }
sys-locale = "0.3"
network-interface = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
easytier = { git = "ssh://git@github.com/Qomicex-Public/EasyTier4QML.git", rev = "9055aef", package = "easytier", default-features = false, features = [
    "aes-gcm",
    "endpoint-discovery",
    "extended-services",
    "management",
    "tcp-hole-punch",
    "zstd",
    "smoltcp",
    "socks5",
    "kcp",
    "quic",
    "faketcp",
    "websocket",
    "wireguard",
    "upnp",
] }
easytier-core = { git = "ssh://git@github.com/Qomicex-Public/EasyTier4QML.git", rev = "9055aef", package = "easytier-core", default-features = false, features = [
    "aes-gcm",
    "endpoint-discovery",
    "extended-services",
    "management",
    "tcp-hole-punch",
    "zstd",
    "proxy-smoltcp-stack",
    "proxy-packet",
    "vpn-portal",
] }
easytier-proto = { git = "ssh://git@github.com/Qomicex-Public/EasyTier4QML.git", rev = "9055aef", package = "easytier-proto", default-features = false, features = ["api", "core", "quic", "faketcp", "websocket", "wireguard"] }

